# Compile python project
name: Python Windows

on:
  push:
    paths:
      - "!.github/**"
      - ".github/workflows/Python_Windows.yaml"
      - "./src/**"
      - "./test/**"
      - "./scripts/**"
  # pull_request:
  #   paths:
  #     - "**"
  #     - "!.github"
  #     - ".github/workflows/Python_Windows.yaml"
  #     - "./**"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    env:
      py_dir: "."
      py_exe: "python"

    defaults:
      run:
        working-directory: ${{ env.py_dir }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: ${{ env.py_exe }} -c "import sys; print(sys.version)"

      - name: Update pip
        run: |
             ${{ env.py_exe }} -m pip install --upgrade pip

      - name: Install dependencies, requirements.txt
        run: |
             ${{ env.py_exe }} -m pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
